Vagrant.configure("2") do |config|
  
  config.vm.define "de", primary: true do |ansnode|
    ansnode.vm.box = "package.box"
	ansnode.vm.hostname = "de"
    ansnode.vm.network "private_network", ip: "10.50.10.10"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "de"
      vb.memory = "1024"
    end
	
	ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
	ansnode.vm.provision "shell", path: "./files/docker.sh"
	
	ansnode.vm.provision "shell", path: "./files/user-slave.sh", args: "appuser"
	ansnode.vm.provision "shell", inline: "sudo usermod -aG docker appuser"

  end

end