version: "3.3"
services:
  post_db:
    container_name: post_db
    image: mongo:3.2
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db

  ui:
    image: ${USERNAME}/ui:1.0
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: pause
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
      placement:
        constraints:
          - node.role == worker
    ports:
      - ${UI_PORTS}
    networks:
    - front_net

  post:
    image: ${USERNAME}/post:1.0
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
        -  post
      back_net:
        aliases:
        -  post

  comment:
    image: ${USERNAME}/comment:1.0
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
        - comment
      back_net:
        aliases:
        - comment

  node-exporter:
    image: prom/node-exporter:v0.15.2
    deploy:
      mode: global
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:

  back_net:
    ipam:
      config:
      - subnet: "10.50.20.0/24"
