dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh | bash
  - docker exec hw-test bash -c './tests/run.sh'
notifications:
  slack: testlanworkspace:EGX8NUPEnnbCBBRIaX8EJwPG