version: "3.3"
services:
  post_db:
    container_name: post_db
    image: mongo:3.2
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db

  ui:
    image: ${USERNAME}/ui:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - ${UI_PORTS}
    networks:
    - front_net

  post:
    image: ${USERNAME}/post:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
        -  post
      back_net:
        aliases:
        -  post

  comment:
   image: ${USERNAME}/comment:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      front_net:
        aliases:
        - comment
      back_net:
        aliases:
        - comment

volumes:
  post_db:

networks:
  front_net:

  back_net:
    ipam:
      config:
      - subnet: "10.50.20.0/24"
