Vagrant.configure("2") do |config|
  
  config.vm.define "de", primary: true do |ansnode|
    ansnode.vm.box = "generic/debian10"
	ansnode.vm.hostname = "de"
    ansnode.vm.network "private_network", ip: "10.50.10.10"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "de"
	  vb.cpus = "2"
      vb.memory = "4096"
    end
	
	ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end
end