---
- block:
  - name: Install Apache on RedHat
    yum: pkg=httpd state=latest
  - name: Enable Apache on system reboot for RedHat
    service: name=httpd state=started
  when: ansible_os_family == "RedHat"

- block:
  - name: Install Apache on Debian
    apt: pkg=apache2 state=latest
  - name: Enable Apache on system reboot for Debian
    service: name=apache2 state=started
  when: ansible_os_family=="Debian"
