---
- hosts: all
  become: yes

  vars:
   source_folder: ./website
   destin_folder: /var/www/html

  tasks:
  - include: install_apache.yml
  - include: copy_site.yml

  handlers:
   - name: Restart Apache RedHat
     service:
       name: httpd
       state: restarted
     when: ansible_os_family=="RedHat"

   - name: Restart Apache Debian
     service:
       name: apache2
       state: restarted
     when: ansible_os_family=="Debian"
