Vagrant.configure("2") do |config|
  
  config.vm.define "ansible", primary: true do |ansnode|
    ansnode.vm.box = "generic/debian10"
	ansnode.vm.hostname = "ansible"
    ansnode.vm.network "private_network", ip: "10.50.10.10"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansible"
      vb.memory = "512"
    end
	
	ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
	ansnode.vm.provision "shell", path: "./files/user.sh", args: "appuser"
		
	ansnode.vm.provision "shell", path: "./files/ansible.sh"
	
	ansnode.vm.provision "1",
	  type:"file",
	  preserve_order: true,
	  source: "../../../ansible",
	  destination: "/tmp/ansible"
	ansnode.vm.provision "2",
	  type:"shell",
	  preserve_order: true,
	  inline: <<-SHELL
        echo "Start copy"
        sudo mv /tmp/ansible /home/appuser/ansible
	    sudo chmod -R 777 /home/appuser/ansible
	    sudo chown -R appuser:appuser /home/appuser/ansible
      SHELL
  end

  config.vm.define "deb" do |app|
    app.vm.box = "generic/debian10"
    app.vm.hostname = "deb"
    app.vm.network :private_network, ip: "10.50.10.20"
	app.vm.provider "virtualbox" do |vb|
      vb.name = "deb"
      vb.memory = "512"
    end
	app.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	app.vm.provision "shell", path: "./files/user-slave.sh", args: "appuser"
  end

  config.vm.define "rh" do |app|
    app.vm.box = "generic/rhel7"
    app.vm.hostname = "rh"
    app.vm.network :private_network, ip: "10.50.10.30"
	app.vm.provider "virtualbox" do |vb|
      vb.name = "rh"
      vb.memory = "512"
    end
	app.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	app.vm.provision "shell", path: "./files/user-slave.sh", args: "appuser"
  end

end