---
- name: Install Apache & make Site
  hosts: all
  become: yes

  vars:
   source_folder: ./website
   destin_folder: /var/www/html

  tasks:
  - block:
    - name: Install Apache on RedHat
      yum: pkg=httpd state=latest
    - name: Enable Apache on system reboot for RedHat
      service: name=httpd state=started
    when: ansible_os_family == "RedHat"

  - block:
    - name: Install Apache on Debian
      apt: pkg=apache2 state=latest
    - name: Enable Apache on system reboot for Debian
      service: name=apache2 state=started
    when: ansible_os_family=="Debian"

  - name: Generate index.html
    template: src={{source_folder}}/index.j2 dest={{destin_folder}}/index.html mode=0555
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian 

  - name: Copy site
    copy: src={{source_folder}}/{{item}}  dest={{destin_folder}} mode=0555
    loop:
      - "index.html"
      - "bahamas.png"
      - "bssr.png"
      - "bulgaria.png"
      - "ussr.png"
    notify:
      - Restart Apache RedHat
      - Restart Apache Debian

  handlers:
   - name: Restart Apache RedHat
     service:
       name: httpd
       state: restarted
     when: ansible_os_family=="RedHat"

   - name: Restart Apache Debian
     service:
       name: apache2
       state: restarted
     when: ansible_os_family=="Debian" 
