Vagrant.configure("2") do |config|
  
  config.vm.define "de", primary: true do |ansnode|
    ansnode.vm.box = "package.box"
	ansnode.vm.hostname = "de"
    ansnode.vm.network "private_network", ip: "10.50.10.10"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "de"
      vb.memory = "1024"
    end
	
	ansnode.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    
	ansnode.vm.provision "shell", path: "./files/docker.sh"
	
	ansnode.vm.provision "shell", path: "./files/user-slave.sh", args: "appuser"
	ansnode.vm.provision "shell", inline: "sudo usermod -aG docker appuser"

	ansnode.vm.provision "1",
	  type:"file",
	  preserve_order: true,
	  source: "../../../docker",
	  destination: "/tmp/docker"
	ansnode.vm.provision "2",
	  type:"shell",
	  preserve_order: true,
	  inline: <<-SHELL
        echo "Start copy"
        sudo mv /tmp/docker /home/appuser/docker
	    sudo chmod -R 777 /home/appuser/docker
	    sudo chown -R appuser:appuser /home/appuser/docker
      SHELL
  


  end
end