version: "3.6"

services:
  post_db:
    container_name: post_db
    image: ${DB_IMAGE}
    volumes:
    - post_db:/data/db
    networks:
      back_net:
        aliases:
        - post_db
        - comment_db

  comment:
    build: ../src/comment/
    container_name: comment
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases: 
        - comment
      back_net:
        aliases: 
        - comment

  post:
    build: ../src/post/
    container_name: post
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      front_net:
        aliases: 
        -  post
      back_net:
        aliases: 
        -  post

  ui:
    build: ../src/ui/
    container_name: ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
    - ${UI_PORTS}
    networks:
    - front_net
  
  prometheus:
    build: ../monitoring/prometheus
    container_name: prometheus
    image: ${USER_NAME}/prometheus:${PROM_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongod_exporter:
    build: ../monitoring/mongodb_exporter
    container_name: mongo-exporter
    image: ${USER_NAME}/mongodb_exporter:${MDB_EXPORTER_VERSION}
    networks:
      back_net:
        aliases:
          - mongo-exporter

  blackbox-exporter:
    build: ../monitoring/blackbox_exporter
    container_name: blackbox-exporter
    image: ${USER_NAME}/blackbox-exporter:${BLACKBOX_VERSION}
    networks:
      back_net:
        aliases:
          - blackbox-exporter
      front_net:
        aliases:
          - blackbox-exporter
  
volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      config:
      - subnet: "10.50.1.0/24"

  back_net:
    ipam:
      config:
      - subnet: "10.50.2.0/24"
