Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
	end
	#config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "docker" do |d|
    d.vm.box = "ubuntu/xenial64"
    d.vm.hostname = "docker"
    d.vm.network :private_network, ip: "10.10.10.100"

    d.vm.provision "ansible" do |ansible|
    	ansible.playbook = "playbooks/gitlab-runner.yml"
    	ansible.groups = {
    		"docker" => ["docker"]
    	}
        ansible.extra_vars = {
            "deploy_user" => "vagrant"
        }
    	
    end
  end
  
end
