---
# tasks file for deploy_apache_web
- block:
#   - name: Install Apache for RedHat
   -  yum: name=httpd state=latest
#   - name: Start Apache for RedHat
   -  service: name=httpd state=started
  when: ansible_os_family == "RedHat"

- block:
#   - name: Install Apache for Debian
   -  apt:
       name: apache2
       state: latest
#   - name: Start Apache for Debian
   -  service: name=apache2 state=started
  when: ansible_os_family=="Debian"

- name: Generate index.html
  template: src=index.j2 dest={{destin_folder}}/index.html mode=0555
  notify:
    - Restart Apache RedHat
    - Restart Apache Debian

- name: Copy site
  copy: src={{item}} dest={{destin_folder}} mode=0555
  loop:
    - "bahamas.png"
    - "bssr.png"
    - "bulgaria.png"
    - "ussr.png"
  notify:
    - Restart Apache RedHat
    - Restart Apache Debian 
